name: scriptkill
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  mobx: 1.2.0
  flutter_mobx: 1.1.0
  shared_preferences: 0.5.3+4
  url_launcher: 5.7.1
  webview_flutter: 0.3.24
  
  flutter_svg: 0.19.0
  carousel_slider: 2.1.0
  fluro: 1.6.3
  provider: 4.3.2
  dio: 3.0.9
  photo_view: 0.9.2
  json_annotation: 3.0.1
  fluttertoast: ^3.1.0
  flutter_easyrefresh: ^2.1.5
  synchronized: ^2.1.0
  flutter_spinkit: "^4.1.2"
  font_awesome_flutter: "^8.8.1"
  cached_network_image: "^2.2.0"
  flutter_staggered_animations: "^0.1.2"
  fluwx: "2.3.0"
  rflutter_alert: ^1.0.3
  device_info : ^0.4.2+8

   # 需要适配设置
  image_cropper: 1.0.2
  image_picker: 0.6.1+4
  permission_handler: 5.0.1+1
  
  image_gallery_saver: ^1.5.0

  flutter_picker: ^1.1.5
  date_format:  ^1.0.8
  wechat_assets_picker: ^4.2.1
  keyboard_dismisser: ^1.0.2

  rxdart: ^0.24.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.10.0
  mobx_codegen: 1.1.0
  json_serializable: 3.3.0
  
  # bot_toast: ^2.0.0+2

  #cached_network_image
# scalable_image 也是一个图片手势放缩效果模块。
#zoomable_image：一个图片手势放缩效果模块。
#timeline：一个时间线的插件。
#flutter_swiper：轮播图组件。


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
   - assets/icon/
   - assets/images/
   - assets/tabbar/   
   - assets/logo/
   - assets/guide/
   - assets/splash/